spring:
  profiles: default

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 15
  client:
    healthcheck:
      enabled: true
    initialInstanceInfoReplicationIntervalSeconds: 1
    instanceInfoReplicationIntervalSeconds: 10
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

feign:
  hystrix:
    enabled: false
---
spring:
  profiles: container

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 15
    ipAddress: ${EUREKA_INSTANCE_IP_ADDRESS}
  client:
    healthcheck:
      enabled: true
    initialInstanceInfoReplicationIntervalSeconds: 1
    instanceInfoReplicationIntervalSeconds: 10
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://${SERVICE_REGISTRY_URL}:${SERVICE_REGISTRY_PORT}/eureka/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

feign:
  hystrix:
    enabled: false
