spring:
  profiles:
    active: default
---
spring:
  profiles: default
  rabbitmq:
      host: ${RABBITMQ_HOST:localhost}
      user: guest
      password: guest
eureka:
  instance:
    appname: boao-promtorg
    hostname: boao-promtorg
server:
  port: ${BOAO_PROMTORG_SERVER_PORT:9081}
rabbitmq:
  names:
    general: general
    priority: priority
  exchange:
    name: exchange-prom
---
spring:
  profiles: container