spring:
  profiles:
    active: default
  rabbitmq:
      host: localhost
eureka:
  instance:
    appname: boao-promtorg
    hostname: boao-promtorg
server:
  port: ${BOAO-PROMTORG_SERVER_PORT:9081}
url:
  message-broker: http:\\test
rabbitmq:
  names:
    general: general
    priority: priority
  exchange:
    name: exchange-prom
---
spring:
  profiles: default
---
spring:
  profiles: test
eureka:
  client:
    enabled: false
---
spring:
  profiles: container

