spring:
  profiles:
    active: default
---
spring:
  profiles: default
server:
  port: ${GATEWAY_SERVER_PORT:9090}
eureka:
  instance:
    appname: gateway
    hostname: gateway
zuul:
  prefix: /gateway/api/v1
  routes:
    boao-promtorg:
      path: /boao-promtorg/**
      serviceId: boao-promtorg
  host:
   connect-timeout-millis: 50000
   socket-timeout-millis: 50000
---
spring:
  profiles: container