spring:
  profiles.active: default
eureka:
  instance:
    appname: gateway
    hostname: gateway
server:
  port: ${GATEWAY_SERVER_PORT:9090}
zuul:
  prefix: /gateway/api/v1
  routes:
    boao-promtorg:
      path: /boao-promtorg/**
      serviceId: boao-promtorg
  host:
   connect-timeout-millis: 50000
   socket-timeout-millis: 50000
---
spring:
  profiles: default

---
spring:
  profiles: container
  zipkin:
    base-url: http://zipkin:9411