spring:
  profiles.active: default
eureka:
  instance:
    appname: gateway
    hostname: gateway
server:
  port: ${GATEWAY_SERVER_PORT:9090}
zuul:
  prefix: /api/v1
  routes:
    quota:
      path: /convert/**
      serviceId: converner1c
  host:
   connect-timeout-millis: 50000
   socket-timeout-millis: 50000
---
spring:
  profiles: default

---
spring:
  profiles: container
  zipkin:
    base-url: http://zipkin:9411
